#!/bin/python

import sys

def divisibleSumPairs(n, k, arr):
    # Complete this function
    arr.sort()
    c = 0
    for i in range(0,len(arr)):
    	for j in range(i+1,len(arr)):
    		if (arr[i]+arr[j]) % k ==0:
    			c +=1
    
    return c			


n, k = raw_input().strip().split(' ')
n, k = [int(n), int(k)]
ar = map(int, raw_input().strip().split(' '))
result = divisibleSumPairs(n, k, ar)
print result
